import Script from 'next/script';

import StyledComponentsRegistry from 'src/lib/registry';

import Nav from '../src/components/shared/Nav';

import { Providers } from './Provider';

import type { Metadata } from 'next';

import 'src/styles/index.scss';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, maximum-scale=1, user-scalable=no, initial-scale=1, shrink-to-fit=no"
        />
      </head>
      <body>
        <Nav />
        <Providers>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </Providers>
        <Script
          src="https://kit.fontawesome.com/4133372eed.js"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
};

export default RootLayout;
